defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  pool: 5

development:
  <<: *defaults
  database: amanikids_website_development

test: &test
  <<: *defaults
  database: amanikids_website_test

cucumber:
  <<: *test
